'use client';
import './globals.css'
import '@/styles/index.scss'
import { Poppins } from 'next/font/google'
import Footer from '@/components/Footer/Footer'
import SiteHeader from './SiteHeader'
import SEO from '@/data/seodata/seo'
import { usePathname } from 'next/navigation'

// export const metadata = {
// 	title: 'Ncmaz - Blog, News, Magazine template',
// 	description: 'Generated by create next app',
// }

const poppins = Poppins({
	subsets: ['latin'],
	display: 'swap',
	weight: ['300', '400', '500', '600', '700'],
})

export default function RootLayout({
	children,
	params,
}: {
	children: React.ReactNode
	params: { slug?: string };
}) {
	const pathname = usePathname();

	const slug = pathname.split('/').filter(Boolean).pop() || 'home';
	return (
		<html lang="en" className={poppins.className}>
			<SEO slug={slug} />
			<head>
				<link
					href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
					rel="stylesheet"
				/>
			</head>
			<body className="">
				<div className="bg-[#f8f8f8] text-base text-neutral-900 dark:bg-neutral-900/95 dark:text-neutral-200">
					<SiteHeader />
					{children}
					<Footer />
				</div>
			</body>
		</html>
	)
}
